=== freight-chain/instruments-api/nft-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "info": {"$ref": "#/definitions/info_type"},
        "item": {"$ref": "#/definitions/item2_type"},
        "event": {"$ref": "#/definitions/event_type"},
        "protocolProfileBehavior": {"$ref": "#/definitions/raw_type"}
    },
    "definitions": {
        "info_type": {
            "type": "object",
            "properties": {
                "_postman_id": {"type": "string"},
                "name": {"type": "string"},
                "description": {"type": "string"},
                "schema": {"type": "string"}
            }
        },
        "exec_type": {
            "type": "array",
            "minItems": 0,
            "items": {"type": "string"}
        },
        "script_type": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "type": {"type": "string"},
                "exec": {"$ref": "#/definitions/exec_type"}
            }
        },
        "event_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "listen": {"type": "string"},
                    "script": {"$ref": "#/definitions/script_type"}
                },
                "required": [
                    "listen",
                    "script"
                ]
            }
        },
        "header_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "key": {"type": "string"},
                    "value": {"type": "string"}
                },
                "required": [
                    "value",
                    "key"
                ]
            }
        },
        "url_type": {
            "type": "object",
            "properties": {
                "raw": {"type": "string"},
                "host": {"$ref": "#/definitions/exec_type"},
                "port": {"type": "string"},
                "path": {"$ref": "#/definitions/exec_type"},
                "query": {"$ref": "#/definitions/header_type"}
            }
        },
        "raw_type": {
            "type": "object",
            "properties": {}
        },
        "options_type": {
            "type": "object",
            "properties": {
                "raw": {"$ref": "#/definitions/raw_type"}
            }
        },
        "body_type": {
            "type": "object",
            "properties": {
                "mode": {"type": "string"},
                "raw": {"type": "string"},
                "options": {"$ref": "#/definitions/options_type"}
            }
        },
        "request_type": {
            "type": "object",
            "properties": {
                "method": {"type": "string"},
                "header": {"$ref": "#/definitions/header_type"},
                "url": {"$ref": "#/definitions/url_type"},
                "description": {"type": "string"},
                "body": {"$ref": "#/definitions/body_type"}
            }
        },
        "response_type": {
            "type": "array",
            "minItems": 0
        },
        "item_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "event": {"$ref": "#/definitions/event_type"},
                    "request": {"$ref": "#/definitions/request_type"},
                    "response": {"$ref": "#/definitions/response_type"}
                },
                "required": [
                    "request",
                    "response",
                    "name",
                    "event"
                ]
            }
        },
        "item2_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "item": {"$ref": "#/definitions/item_type"},
                    "description": {"type": "string"},
                    "protocolProfileBehavior": {"$ref": "#/definitions/raw_type"}
                },
                "required": [
                    "protocolProfileBehavior",
                    "item",
                    "name",
                    "description"
                ]
            }
        }
    }
}

=== freight-chain/instruments-api/nft-postman.json
{
	"info": {
		"_postman_id": "7ff4503e-e414-402e-9a87-9b89b4a9fc33",
		"name": "Freight Trust Non Fungible Documents of Trade",
		"description": " FT-This is the api reference for the Freight Trust dApp which allows recording, transfering and signing of documents of trade.",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "nft",
			"item": [
				{
					"name": "Returns the token contract's name",
					"event": [
						{
							"listen": "test",
							"script": {
								"id": "579475a4-dc18-4d32-aac1-f93f79607164",
								"exec": [
									"pm.test(\"Returns the right name\", function () {",
									"    response = pm.response.json();",
									"    pm.expect(response[\"name\"]).to.eql(\"Documents of Trade\");",
									"});"
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"url": {
							"raw": "localhost:3000/nft/name",
							"host": [
								"localhost"
							],
							"port": "3000",
							"path": [
								"nft",
								"name"
							]
						}
					},
					"response": []
				},
				{
					"name": "Returns the token contract's symbol",
					"event": [
						{
							"listen": "test",
							"script": {
								"id": "d700d7ea-b3b2-4b09-b41d-0864ce4d107a",
								"exec": [
									"pm.test(\"Returns the right symbol\", function () {",
									"    response = pm.response.json();",
									"    pm.expect(response[\"symbol\"]).to.eql(\"DOT\");",
									"});"
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"url": {
							"raw": "localhost:3000/nft/symbol",
							"host": [
								"localhost"
							],
							"port": "3000",
							"path": [
								"nft",
								"symbol"
							]
						}
					},
					"response": []
				},
				{
					"name": "An API endpoint to get the total supply of tokens in the ERC721 contract",
					"event": [
						{
							"listen": "test",
							"script": {
								"id": "7a4ced55-4a8d-42ce-b3db-6d6b8da24ff1",
								"exec": [
									"pm.test(\"Returns the right type\", function () {",
									"    response = pm.response.json();",
									"    pm.expect(uintVerify(response[\"totalSupply\"])).to.eql(true);",
									"});",
									"",
									"function uintVerify(proposed){",
									"  proposed = parseInt(proposed, 10);",
									"  return ((proposed >= 0) && (proposed < 115792089237316195423570985008687907853269984665640564039457584007913129639935))",
									"}"
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"url": {
							"raw": "localhost:3000/nft/totalSupply",
							"host": [
								"localhost"
							],
							"port": "3000",
							"path": [
								"nft",
								"totalSupply"
							]
						},
						"description": "Returns the total supply of Non fungible tokens"
					},
					"response": []
				},
				{
					"name": "Returns the Token URI",
					"event": [
						{
							"listen": "test",
							"script": {
								"id": "f20a8058-89d6-457c-b611-276db0739470",
								"exec": [
									"function bytesVerify(proposed, bytes){ //proposed is the string to be checked, bytes is the byte size of the encoded data",
									"  return ((typeof proposed == \"string\") && (proposed.length == 2*bytes+2) && isHexStrict(proposed))",
									"}",
									"",
									"function isHexStrict(proposed){//I wrote a clone of web3.isHexStrict, so we don't have to run a node to test code",
									"  proposed = proposed.toLowerCase()",
									"  flag = (proposed.slice(0,2) == \"0x\")",
									"  for(i = 2;  i < proposed.length; i ++){",
									"    test = proposed.charAt(i)",
									"    flag = flag && (test <= '9' || ((test>='a')&&(test<='f')))",
									"  }",
									"  return flag",
									"}",
									"",
									"pm.test(\"Rejects Invalid Data Types\", function () {",
									"    if(bytesVerify(pm.variables.get(\"tokenId\"), 32)){",
									"        pm.expect(pm.response.code).to.be.oneOf([200, 425]);",
									"    }else{",
									"        pm.expect(pm.response.code).to.be.oneOf([400, 425]);",
									"    }",
									"});",
									"",
									"pm.test(\"Returns the Right Type\", function () {",
									"    if(responseCode.code == 200){",
									"        response = pm.response.json();",
									"        pm.expect(typeof response[\"tokenURI\"]).to.eql(\"string\");",
									"    } else if (responseCode.code == 400) {",
									"        pm.response.to.have.body(\"Invalid Input\")",
									"    }  ",
									"})"
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"url": {
							"raw": "localhost:3000/nft/tokenURI/?tokenId={{tokenId}}",
							"host": [
								"localhost"
							],
							"port": "3000",
							"path": [
								"nft",
								"tokenURI",
								""
							],
							"query": [
								{
									"key": "tokenId",
									"value": "{{tokenId}}"
								}
							]
						}
					},
					"response": []
				},
				{
					"name": "Returns an interface's support status",
					"event": [
						{
							"listen": "test",
							"script": {
								"id": "3d18a808-f86d-4934-ac6c-ca7fb9d46468",
								"exec": [
									"function bytesVerify(proposed, bytes){ //proposed is the string to be checked, bytes is the byte size of the encoded data",
									"  return ((typeof proposed == \"string\") && (proposed.length == 2*bytes+2) && isHexStrict(proposed))",
									"}",
									"function isHexStrict(proposed){//I wrote a clone of web3.isHexStrict, so we don't have to run a node to test code",
									"  proposed = proposed.toLowerCase()",
									"  flag = (proposed.slice(0,2) == \"0x\")",
									"  for(i = 2;  i < proposed.length; i ++){",
									"    test = proposed.charAt(i)",
									"    flag = flag && (test <= '9' || ((test>='a')&&(test<='f')))",
									"  }",
									"  return flag",
									"}",
									"",
									"pm.test(\"Rejects Invalid Data Types\", function () {",
									"    if(bytesVerify(pm.variables.get(\"interfaceId\"), 4)){",
									"        pm.response.to.have.status(200);",
									"    }else{",
									"        pm.expect(pm.response.code).to.be.oneOf([400, 425]);",
									"    }",
									"});",
									"",
									"pm.test(\"Returns the Right Type\", function () {",
									"    if(responseCode.code == 200){",
									"        response = pm.response.json();",
									"        pm.expect(typeof response[\"supported\"]).to.eql(\"boolean\");",
									"    } else if (responseCode.code == 400) {",
									"        pm.response.to.have.body(\"Invalid Input\")",
									"    }  ",
									"})"
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"url": {
							"raw": "localhost:3000/nft/supportsInterface/?interfaceId={{interfaceId}}",
							"host": [
								"localhost"
							],
							"port": "3000",
							"path": [
								"nft",
								"supportsInterface",
								""
							],
							"query": [
								{
									"key": "interfaceId",
									"value": "{{interfaceId}}"
								}
							]
						}
					},
					"response": []
				},
				{
					"name": "Returns the token identifier of the `index`-th nft tracked by the contract",
					"event": [
						{
							"listen": "test",
							"script": {
								"id": "6b173a5a-2304-4c7c-8e52-d00829dafe1f",
								"exec": [
									"function bytesVerify(proposed, bytes){ //proposed is the string to be checked, bytes is the byte size of the encoded data",
									"  return ((typeof proposed == \"string\") && (proposed.length == 2*bytes+2) && isHexStrict(proposed))",
									"}",
									"",
									"function isHexStrict(proposed){//I wrote a clone of web3.isHexStrict, so we don't have to run a node to test code",
									"  proposed = proposed.toLowerCase()",
									"  flag = (proposed.slice(0,2) == \"0x\")",
									"  for(i = 2;  i < proposed.length; i ++){",
									"    test = proposed.charAt(i)",
									"    flag = flag && (test <= '9' || ((test>='a')&&(test<='f')))",
									"  }",
									"  return flag",
									"}",
									"",
									"pm.test(\"Rejects Invalid Data Types\", function () {",
									"    if(bytesVerify(pm.variables.get(\"index\"), 32)) {",
									"        pm.expect(pm.response.code).to.be.oneOf([200, 425]);",
									"    }else{",
									"        pm.expect(pm.response.code).to.be.oneOf([400, 425]);",
									"    }",
									"});",
									"",
									"pm.test(\"Returns the Right Type\", function () {",
									"    if(responseCode.code == 200){",
									"        response = pm.response.json();",
									"        pm.expect(uintVerify(response[\"token\"])).to.eql(true);",
									"    } else if (responseCode.code == 400) {",
									"        pm.response.to.have.body(\"Invalid Input\")",
									"    }  ",
									"})"
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"url": {
							"raw": "localhost:3000/nft/tokenByIndex/?index={{index}}",
							"host": [
								"localhost"
							],
							"port": "3000",
							"path": [
								"nft",
								"tokenByIndex",
								""
